Add PumpProbePulses for combined FEL/PPL pulse patterns
European-XFEL/EXtra pull request #24
Opened 2023-07-21 12:59 UTC by philsmt

The third component in the mix for pump-probe experiments 🔦 

* Combines FEL and PPL pulses into a single linear pattern
* Move PPL pulses to their _true_ location by fixed bunch table position or relative bunch table/pulse distance to first FEL pulse 
* Extends the `MultiIndex` by two boolean fields `fel` and `ppl` to distinguish between respective shots

This is not entirely done yet, but for sanity's sake I want to organize all the various almost-ready EXtra stuff in branches and PRs 🤯 

Open questions / ToDo:
* Currently some APIs are inconsistent in output format, `.trains()` returns two unlabelled arrays of pulse IDs for FEL/PPL respectively rather than one, while `.peek_pulse_ids()` just returns a single combined unlabelled array. Maybe having labelled arrays with just the boolean flags would be better generally, or with an index like the one `.get_pulse_ids()` returns
* `.get_pulse_mask()` is built on top of iterating via `.trains()`, should look into performance numbers for very long runs
* Error handling when the chosen synchronization method for PPL pulses is not possible (e.g. there is no FEL pulse to offset to)
* Tests

2023-08-15 12:49 UTC, philsmt commented
Re-implemented this now on top of the new `PulsePattern` based on Pulse IDs, which made the code **much** simpler. It still makes use of the `in8`-view trick, but only ofr the purpose of pattern comparisons.

Ready for review now with tests.

2023-08-16 18:04 UTC, JamesWrigley requested changes
Mostly being very nitpicky about typos :mag: This should also be documented in `components.md` and have a changelog entry.

2023-08-17 07:30 UTC, philsmt commented on src/extra/components/pulses.py
> +    This components offers support for arbitrary pulse relations between
Thanks, fixed in baa7edf.

2023-08-17 07:30 UTC, philsmt commented on src/extra/components/pulses.py
> +    3) Offset all PPL pulses relative to the first FEL pulse in units in
Thanks, fixed in baa7edf.

2023-08-17 07:30 UTC, philsmt commented on src/extra/components/pulses.py
> +    Unlike [XrayPulses] and [OpticalLaserPulses], this component adds
Thanks, fixed in baa7edf.

2023-08-17 07:43 UTC, philsmt commented
Thanks! Somehow I'm still forgetting to document the changes.

2023-08-17 08:24 UTC, JamesWrigley commented on src/extra/components/pulses.py
> +class PumpProbePulses(XrayPulses, OpticalLaserPulses):
Ok, that sounds reasonable :+1: I'd maybe just add a comment to the class warning people to be careful about using `super()`.

2023-08-17 09:59 UTC, JamesWrigley approved these changes
I'd add an internal comment about `super()` (https://github.com/European-XFEL/EXtra/pull/24#discussion_r1296856672), but otherwise LGTM!

2023-08-17 12:02 UTC, philsmt commented
I hope I didn't get carried away in 24400ea :grin:

2023-08-28 16:19 UTC, philsmt commented
Awesome, happy to hear!

> * For some runs (e.g. p4451, run 78) there were more laser pulses configured than FEL pulses, which was slightly confusing when plotting the pulse pattern because there would be more points than pulses:
> [img]
>   What I'm typically looking for is the combination of FEL/PPL pulses, so what if `peek_pulse_ids()` had something like a 
`only_with_fel=True` argument to drop PPL pulses without an FEL pulse?

Would you have the same result with `pp_pulses.peek_pulse_ids()[:, True]`, i.e. all pulses with `fel=True`?

> * `PumpProbePulses._get_ppl_offset()` fails if the pulse offset is specified and there's only one pulse (e.g. p4451, run 80), because on line 923 it tries to look at the second pulse. I worked around it with:
>   ```diff
>        elif self._pulse_offset is not None:
>   -         return fel[0] + int((fel[1] - fel[0]) * self._pulse_offset)
>   +        if len(fel) > 1:
>   +            return fel[0] + int((fel[1] - fel[0]) * self._pulse_offset)
>   +        else:
>   +            return fel[0]
>   ```

Hmm, but that moves the PPL pulses for `pulse_offset != 0` to a different position then expected. The offset cannot be inferred in units of pulses if there is always only a single pulse (for intermittent cases there's `extrapolate=True`), unless we'd add a manual override for repetition rate in such a case.

2023-12-05 11:12 UTC, merged