Add DldPulses interface for pulse information in reconstructed DLD data
European-XFEL/EXtra pull request #42
Opened 2023-08-08 15:35 UTC by philsmt

First `PulsePattern` implementation based on the new and simpler interface.

The offline calibration based REMI/DLD reconstruction adds pulse information to the output files that *may* be different than the one obtained from timeserver data due to particular configurations chosen for reconstruction at the time. This compoent allows to read this data and expose it via the very same interface.

2023-08-08 16:07 UTC, JamesWrigley requested changes
Minor nitpicking :mag: This should also be documented in `components.md`.

2023-08-09 06:12 UTC, philsmt commented on src/extra/components/pulses.py
> +            print(f'{self.__class__.__name__}._get_pulse_ids(): No actual '
It does, but it runs into the same problem we had in EXtra-data with automatic aliases - it's hidden by default. I'm fine with removing if you feel strongly about it, but I see no other way to *really* make it visible for those that may trip over it during an analysis.

2023-08-09 06:12 UTC, philsmt commented on docs/changelog.md
> +- [DldPulses][extra.components.DldPulses] to access pulse information saved during delay line detector event reconstruction (!42).
Oops!

2023-08-09 08:19 UTC, JamesWrigley commented on src/extra/components/pulses.py
> +            print(f'{self.__class__.__name__}._get_pulse_ids(): No actual '
Ah right I forgot about that, NVM then.

2023-08-09 08:20 UTC, JamesWrigley approved these changes
LGTM!

2023-08-09 09:24 UTC, philsmt commented
Thank you!

2023-08-09 09:26 UTC, merged